### ISSUE TITLE
Discontinue plugin-google-analytics due to the UA sunset

### ISSUE THREAD

**Issue by bohyunjung** [facebook/docusaurus#10332]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

# Description
Universal Analytics [has officially sunset](https://support.google.com/analytics/answer/11583528) as of the week of July 1, 2024.

This makes the built-in [plugin-google-analytics](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics) obsolete, so there's no need to keep this plugin within the future project releases.

\+ Some outbound links within the project are broken due to the recent change to google developers document. For example, https://developers.google.com/analytics/devguides/collection/gtagjs/#install_the_global_site_tag should be replaced to https://developers.google.com/tag-platform/gtagjs/install

# Task Details
- [ ] Remove packages/docusaurus-plugin-google-analytics
- [ ] Remove the dependency from docusaurus-preset-classic
- [ ] Update the docs
  - [ ] Remove the plugin doc
  - [ ] Remove the references to it
  - [ ] Reorder the [Plugins](https://docusaurus.io/docs/api/plugins) sidebar
- [ ] Update broken Google links from the comments and docs

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
Thanks

Yes we'll remove that plugin but it's technically a breaking change so it will be done for v4.

The plugin is already deprecated in our docs: https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-google-analytics

**Comment by bohyunjung** [comment]
@slorber Thank you for the triage.

It appears that the codebase is not yet accepting PRs for v4. Therefore, I'll leave the plugin itself as-is for now.

In the meantime, I'd like to propose making a PR with the following small changes:

1. Fix broken outbound links to Google Developers Documentation
2. Update some expressions in the plugin documentation to reflect that Universal Analytics (UA) is completely obsolete

What are your thoughts on this approach?

**Comment by slorber** [comment]
Thanks but I think it's fine in the current state, this warning is big enough 

![CleanShot 2024-07-23 at 15 04 45](https://github.com/user-attachments/assets/af1c1dc5-2e1d-46ca-82e3-1e3532bec718)

And broken links such as this one do not seem like a big deal either considering it prints "Service Unavailable":
https://developers.google.com/analytics/devguides/collection/analyticsjs/

It's not super useful to improve a page that we plan to remove soon

**Comment by bohyunjung** [comment]
Thanks for the quick feedback. I agree that these changes aren't necessary for the deprecated plugin at this time.

I'd like to note that the active [plugin-google-gtag](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag) also has a broken link in its documentation:

- Current (broken): https://developers.google.com/analytics/devguides/collection/gtagjs/
- Suggested fix: https://developers.google.com/tag-platform/gtagjs

If it's reasonable to fix this now, I'm happy to do so. Otherwise, I can keep this in mind for the v4 update.

**Comment by slorber** [comment]
Thanks, we'd want to fix this one indeed! (for all our docs versions). PR welcome.

It's weird that Google breaks links. They even discontinued their own link shortener recently. 😅
