### ISSUE TITLE
@docusaurus/Head meta contains data-rh=true, which leads to verification error in Baidu.com and Sogou.com

### ISSUE THREAD

**Issue by travisbikkle** [facebook/docusaurus#10682]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

<meta> generated with @docusaurus/Head is like:

```
<meta name="xxxxxx-verification" content="xxxxxx" data-rh="true">
```

Some search engines requires
```
<meta name="xxxxxx-verification" content="xxxxxx">
```
, and they are not smart enough verify a meta with data-rh.

### Steps to reproduce
```
import Head from '@docusaurus/Head';
        <Head>
            <meta name="baidu-site-verification" content="codeva-xxxxx" />
            <meta name="sogou_site_verification" content="xxxxx" />
        </Head>
```
### Expected behavior

Although those search engines are stupid, but we also should not add anything we won't use.
Please remove the "data-rh" property.

```
<meta name="xxxxxx-verification" content="xxxxxx">
```

### Actual behavior

```
<meta name="xxxxxx-verification" content="xxxxxx" data-rh="true">
```

### Your environment

- Public source code:
- Public site URL: https://mactoys.eusoftbank.com
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
This is not added by us. Please report to https://github.com/staylor/react-helmet-async instead. It looks like they already have https://github.com/staylor/react-helmet-async/issues/12
