### ISSUE TITLE
Docathon August 2017: Master Issue List

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/docusaurus#29]
Use this to come up with issues and items we want to close during this docathon

- [x] Logo (@ericnakagawa) 
- [ ] Sidebar content (see below for details)
- [x] Landing Page - Includes icons/graphics, CSS (@ericnakagawa)
- [x] Footer
- [ ] Help Page
- [x] Site look and feel - (@ericnakagawa)
- [x] Site launch (Cloudflare, SSL, nameservers) (@JoelMarcey)
- [ ] CircleCI or Travis to actually publish the docusaurus.io website
- [ ] Remove noindex meta tag from Head.js before launch (@JoelMarcey)
- [x] Finalize Jest PR (@ericnakagawa)
