### ISSUE TITLE
Migrate all packages to TypeScript

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5817]
## 💥 Proposal

Our TypeScript coverage now has reached 80%+. Recent attempts:

- mdx-loader (migrate): #5347
- theme-classic (complete): #5459
- plugin-debug (migrate): #5465 
- preset-classic (migrate): #5579 

And chores left:

- [x] core (complete): ~~missing `theme-fallback`~~ #6511
- [x] ideal-image (complete): ~~missing theme~~ — Thanks @armano2! #5940
- [x] plugin-pwa (migrate): ~~not migrated at all~~ — Thanks @armano2! #5941
- [x] remark-plugin-npm2yarn (migrate): not easy to migrate, Remark plugin is hard to type ~~To anyone who ever thinks about this: be prepared. It's just 80 lines, but my three attempts to migrate it all ended up in a pathetic sea of red squiggly lines. Remark plugins are born to be JS, and just let it be. Can't believe I did it for mdx-loader—that's already _remarkable_ enough~~ Thanks @duanwilliam! #5931
- [X] live-codeblock (migrate): #5851
- [x] search-algolia (migrate): ~~not migrated at all~~ — Thanks @armano2! #5935

Migration should be done after #5612 where we can make the theme transpiled more easily, or after #5816 where we can probably make the two transpilation targets more similar.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by slorber** [comment]
Awesome, thanks for your work on this ❤️
