### ISSUE TITLE
Safari 15 Requesting a Desktop Website redirects to main site for i18n staging

### ISSUE THREAD

**Issue by timocov** [facebook/docusaurus#6074]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Safari redirects to a wrong domain when you request Desktop Website. I tried ios v15.1.1 and ipados 15.2 (currently in beta). It seems that it is related to `og:url` meta tag which is in the website's HTML content.

I admit that it may be a bug of Safari itself but I just wanted to note this bug here, feel free to close it.

### Steps to reproduce

1. Open https://docusaurus-i18n-staging.netlify.app/ in Safari on iOS or iPadOS (I tried both)
2. Request Desktop Website via `aA` button in the header

### Expected behavior

Safari refreshes the same page and opens it in different view/with different settings for that view.

### Actual behavior

Safari redirects to a page on https://docusaurus.io/ instead.

### Your environment

- Public source code: 
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Safari 15.1, Safari 15.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): iOS 15.1, iPadOS 15.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
I have no idea what you mean by "request desktop website" and don't see any aA button in Safari desktop

![image](https://user-images.githubusercontent.com/749374/145376275-54b9aaf3-99f7-459f-81e1-2e3590572d59.png)


I don't have any iOS device atm, please show a screenshot or explain better

**Comment by slorber** [comment]
If there's a problem in our `og:url`, can you let me know which page has an incorrect value, which value it should be, and why?

**Comment by slorber** [comment]
Note: if this is a problem only appearing in docusaurus-i18n-staging.netlify.app it's likely because we didn't use the correct `config.url` param

It's not so important as it's a staging deployment (deploy previews also have this prod URL. Production Docusaurus websites shouldn't have any problem.

Now if this annoys you in your translation workflow work, we can still do something about it 🤷‍♂️ let me know

**Comment by Josh-Cena** [comment]
This is a feature in Safari 15, my feeling is that this is an escape hatch they used for sites with bad Safari 15 support because of the layout updates. https://appleinsider.com/articles/21/11/03/how-to-request-desktop-versions-of-websites-in-safari-on-iphone-and-ipad

I just realized there's no Safari 15 mobile emulator on desktop, but I can confirm that it's a valid issue.

Safari can send different UA headers to the URL specifying if it's a desktop Safari or a mobile one, and "request desktop site" would re-send a request with the desktop UA. However, seems they actually respect the `og:url` meta rather than the URL the user is currently on. I think this has its goods and bads. Anyways, because docusaurus-i18n-staging.netlify.app has its URL pointing to docusaurus.io, the latter is returned.

This isn't an issue though, because we use responsive layout, not building different sites (I think Reddit does that?). @timocov does it actually affect you in any way? Or are you just trying out cool features?

**Comment by timocov** [comment]
> @timocov does it actually affect you in any way? Or are you just trying out cool features?

@Josh-Cena Not at all. I was just playing locally with our website built with docusaurus and noticed this strange behaviour. Then I checked with docusaurus website to check that we configure our website correctly and faced the same issue so that's why I created this ticket. If it is related to an incorrect configuration, please feel free to close this issue.

> However, seems they actually respect the og:url meta rather than the URL the user is currently on. 

Is this a correct behaviour of the browser or I should create an issue in webkit bug tracker for that? It doesn't look obvious that Safari respects this meta tag more than current URL...

**Comment by Josh-Cena** [comment]
> Is this a correct behaviour of the browser or I should create an issue in webkit bug tracker for that? It doesn't look obvious that Safari respects this meta tag more than current URL...

I guess they must have some reasons, but it's hard to put down in words. Basically, the URL the user is currently on can be a non-canonical URL that you shouldn't send further requests to, or something like that.

I'll close it for now. Thanks for letting us know about this, an interesting exploration for me as well 👍

**Comment by timocov** [comment]
Thanks for help!

> I guess they must have some reasons, but it's hard to put down in words. Basically, the URL the user is currently on can be a non-canonical URL that you shouldn't send further requests to, or something like that.

Even it might look strange for a user (why refreshing the page works differently), I created a ticket in webkit bug tracker, maybe they will put some light on this issue https://bugs.webkit.org/show_bug.cgi?id=234074.

**Comment by Josh-Cena** [comment]
Note that it's probably not `og:url` but canonical URL, this one:

```html
<link data-react-helmet="true" rel="canonical" href="https://docusaurus.io/">
```
