### ISSUE TITLE
Pages with noindex meta still showing in sitemap

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#6247]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

It is bad practice to add noindex pages to sitemap:

- https://sitebulb.com/hints/xml-sitemaps/noindex-url-in-xml-sitemaps/#:~:text=If%20a%20URL%20is%20noindex,in%20unintended%20URLs%20getting%20indexed
- https://support.google.com/webmasters/thread/78460212/is-meta-robots-noindex-for-page-listed-in-sitemap-xml-ok?hl=en

### Steps to reproduce

1. Add `<meta name="robots" content="noindex">` to the head tag of a page.
2. Build.

### Expected behavior

The sitemap doesn't include that page.

### Actual behavior

It does—we don't filter routes by `noindex`.

We should definitely conform to the `noIndex` config option and not output a sitemap in that case. For individual pages, we should probably read the HTML files and filter those with `noindex`? Or should we ask the user to provide a list of routes to ignore? (I think we should have both)

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
> For individual pages, we should probably read the HTML files and filter those with noindex?

I don't like this idea a lot 😅 

Although we might also need to read HTML files for the RSS feed content with MDX, see https://github.com/facebook/docusaurus/issues/5664#issuecomment-948431916 (some code could be shared, need to take care of HTML output file patterns etc)

---

Another possibility is to do something similar to the broken link checker: add some extra logic to the `<Head>` component and notify the parent SSR renderer when a page is using a noIndex meta: we'd get a list of noIndes pathnames after Webpack compilation that we could pass to the sitemaps plugin. This could be good enough and transparent for the user, no extra API needed?

**Comment by Josh-Cena** [comment]
That sounds good as well! 👍

**Comment by deployn** [comment]
Hello, I'm still encountering this problem, unfortunately. Is it currently somehow possible to exclude certain pages from the sitemap? I would like to not have to edit them manually every time after the build process.

**Comment by Josh-Cena** [comment]
@deployn We'll soon have https://github.com/facebook/docusaurus/pull/6979 which will be what you want. For now, there's probably no way to do it.
