### ISSUE TITLE
Cannot generate meta tag

### ISSUE THREAD

**Issue by heowc** [facebook/docusaurus#6735]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I tried to use `ThemeConfig/Metadata[]` but it doesn't seem to work.

### Steps to reproduce

See https://docusaurus.io/ko/docs/next/seo#global-metadata

### Expected behavior

Add meta tag

### Actual behavior

Not add meta tag

### Your environment

- Public source code: -
- Public site URL: - 
- Docusaurus version used: 2.0.0-beta.15
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16.4
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by heowc** [comment]
This seems to be misrepresented in the documentation.

The documentation says it is `metadata` , but it is actually `metadatas` .

**Comment by Josh-Cena** [comment]
Hi, are you using the latest version? We have renamed `metadatas` to `metadata` a few versions ago, see #5871. It works in our website.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/55398995/154958621-697d7816-d749-4229-86c1-890f8d6fcea6.png">

```js
module.exports = {
  themeConfig: {
    metadata: [{name: 'foo', content: 'bar'}],
  },
};
```
