### ISSUE TITLE
Meta description is often truncated

### ISSUE THREAD

**Issue by ArthurFlageul** [facebook/docusaurus#7132]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I've noticed that many of my pages' descriptions are truncated in Google, and other SEO plugins. 
It's often related to the presence of an <a> tag, it seems for example:

The description of [this example page](https://docs.talon.one/docs/product/applications/finding-coupons/)  
<img width="600" alt="Screenshot 2022-04-08 at 09 18 31" src="https://user-images.githubusercontent.com/28596581/162384438-784207b6-658a-4b1b-9c17-302812c0b93a.png">

While my whole first paragraph is
>Click Coupon Finder in the left-side menu of your Application to search for a [coupon code](https://docs.talon.one/docs/product/campaigns/coupons/coupon-page-overview), see all its details and [edit it](https://docs.talon.one/docs/product/campaigns/coupons/managing-coupons#editing-a-coupon). You can search for any coupon in any of the campaigns of the Application.

### Steps to reproduce

I use the following content:

```
---
title: Finding coupons
---

Click **Coupon Finder** in the left-side menu of your Application to search for a
[coupon code](/docs/product/campaigns/coupons/coupon-page-overview), see all its details and
[edit it](/docs/product/campaigns/coupons/managing-coupons#editing-a-coupon). You can search for
any coupon in any of the campaigns of the Application.

1. Type the coupon code or a part of it. The search is case insensitive.
1. Click **Search**.

You see the coupons matching what you typed on the search bar.

:::note
If you entered the full code,
you see the coupon details directly. If you only typed part of the code, you see a list of all
possible coupons and the campaign they belong to.
:::
```

### Expected behavior

The description in search engines goes up tho the maximum amount of characters allowed (150 or so?).

### Actual behavior

The descriptions stops at the first link.

### Your environment

- Public source code: Not public but I can share whatever might be needed.
- Public site URL: https://docs.talon.one
- Docusaurus version used: 2.0.0-beta.18

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, the default description generation takes the first line and makes best effort to convert it to plain text. It is _not_ meant to be fully functional.

https://github.com/facebook/docusaurus/blob/9145ae88cc22ad322e070b705ee3c4c8ef8f0a0a/packages/docusaurus-utils/src/markdownUtils.ts#L44-L54

Where it fails, you should provide your own description through front matter. See https://docusaurus.io/docs/seo#single-page-metadata

**Comment by Josh-Cena** [comment]
You can also easily make it better by not wrapping your text at 80 characters, because our description-parsing is line-based, not paragraph-based.

**Comment by ArthurFlageul** [comment]
Oh that's good to know. I'll try and send a docs update to mention that more prominently. Thank you!
