### ISSUE TITLE
Classic Theme incorrectly overwrites og:image meta tag

### ISSUE THREAD

**Issue by wparad** [facebook/docusaurus#8349]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When the `image` front matter is specified in a blog post or a docs article, and the `themeConfig` specifies the default metadata `og:image`, the theme incorrectly always overwrites the `og:image` meta tag in the built pages.

### Steps to reproduce

Repro of the configuration:

blogpost.md:
```md
---
image: whatever.img
---
```

docusaurus.config.js:
```js
/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'The place',
  tagline: 'The tagline',
  url: 'https://whereever.com/',
  baseUrl: '/',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/favicon.ico',

  // Even if you don't use internalization, you can use this field to set useful
  // metadata like html lang. For example, if your site is Chinese, you may want
  // to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: 'en',
    locales: ['en']
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js')
        },
        blog: {
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css')
        }
      })
    ]
  ],

  // https://docusaurus.io/docs/api/themes/configuration
  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      metadata: [
        { name: 'og:image', content: 'https://authress.io/knowledge-base/img/getting-started.jpg' },
      ]
  })
};
module.exports = config;
```

### Expected behavior

`image` front matter to take precedence over global metadata default.

### Actual behavior

The `metadata` `og:image` overwrites the locally defined `image` value.

### Self-service

- [x] I'd be willing to fix this bug myself. (But only if someone tells me where this code is, I have zero idea what I'm looking for)

**Comment by wparad** [comment]
Your repro screenshot doesn't match the issue ticket description. From yours it says `image: 'img/docusaurus-social-card.jpg'`, but in mine I wrote specifically:

```json
metadata: [
        { name: 'og:image', content: 'https://authress.io/knowledge-base/img/getting-started.jpg' },
      ]
```

I can easily switch to the `image` property to see if that fixes it, but as it is, it would be good if you could try to repro it with specifically the metadata specified.

**Comment by slorber** [comment]
Ok I understand.

Actually it's by design that this metadata field overrides any defaults that the theme set, and it is documented.


<img width="1048" alt="CleanShot 2022-11-17 at 14 45 53@2x" src="https://user-images.githubusercontent.com/749374/202462654-0d5dd0e1-07cf-4b92-810e-0d0c0bdfdc22.png">

**Comment by wparad** [comment]
What's the use case for that? How does that make sense?

We want to set fallbacks for everything, how do we do that correctly?

**Comment by slorber** [comment]
As far as I remember, `themeConfig.metadata` was initially introduced as a way to override the default `<meta name="twitter:card" content="summary_large_image" />` that the theme sets.

Remember theme metadata is not a site-wide metadata, and a Docusaurus site might use multiple themes with different configs and layouts. 

Passing this theme metadata remains a default, and will always be overridden by document-specific metadata (including description). If you don't like that behavior you'll have to implement your "force metadata" behavior with swizzle, but IMHO it makes sense that if you set a description on each doc that description is used in priority over your generic theme metadata that will be only used as a global fallback when you forgot to set a page description.

---

If you want to set a global site metadata for a whole site, you'd rather use the [headTags](https://docusaurus.io/docs/api/docusaurus-config#headTags) API.

I'm not 100% sure but as far as I remember metadata are applied/overriden in this order:
- Core metadata hardcoded
- Core headTags metadata
- Theme metadata hardcoded (like the opinionated twitter:card display)
- themeConfig.metadata (gives the ability to override twitter:card display)
- blog/docs/page layout metadata (may be no metadata but can be added with swizzle
- docs specific metadata

If all this doesn't make sense to you and you have a better proposal, please write down an exhaustive proposal on why a change is needed, and how it should be designed.

IMHO the current system is fine and works as intended, but I admit it can be a bit confusing.

Your image use-case has a better first-class API already.

Your description use-case looks quite artificial to me, and I see no reason for anyone to want that description overridden (ie all your pages have the exact same description). What is the goal here?

**Comment by wparad** [comment]
I think there are some actual things missing here:
* having both `image` in the `themeConfig` and `og:image` in the metadata, creates two different `og:image` <meta> tags, and same goes for any blog or dog with an `image` front matter attribute
* Adding the `head metadata` https://docusaurus.io/docs/markdown-features/head-metadata AND the `image` front matter to a post also creates two `og:image` tags, without the Head metadata, two `og:image` tags are still created, with the second being the themeConfig metadata override.
* layout specific metadata overwrites - It seems there is no way to do this except with the swizzle and it seems reasonable to me I want to do this. For instance I want the the theme override `twitter:card` to be `summary` but leave the `summary_large_image` for both the `blog` and the `docs`. I don't see a way of doing that without the swizzle


I think that means there are two "bugs":
* the `metadata` property of the theme just doesn't really work, I can't find a use for it, unless, literally no other component creates the same meta tag, but since others are likely to do that, we'll end up with "two" of them in a lot of cases, unless it is overwritten in the exact same way. `image` is the biggest culprit because we allow it to populate the `og:image`, anything in the front matter that can populate head metadata, is going to suffer this problem.
* There is no way to set the `twitter:card` type for a whole layout, blog, docs, etc... it can either be set at the theme OR at the individual post level. The problem here is that it can't actually be set at the theme level because it will overwrite everything.

Did I get that correct?

**Comment by slorber** [comment]
Please create repros for every case that you report, so that I can inspect those in practice.

Please avoid creating artificial use-cases. Don't use metadata image if there's themeConfig.image, or if you do, please justify your motivation do not use the API that is designed exactly for this use-case.

React-Helmet-Async is supposed to deduplicate metadata instead of inserting 2 tags, and in my experience it has worked well so far.

We do set 2 (eventually more in the future) metadata when you use the `image` API or frontMatter:

```jsx
      {pageImage && <meta property="og:image" content={pageImage} />}
      {pageImage && <meta name="twitter:image" content={pageImage} />}
```

---

> layout specific metadata overwrites - It seems there is no way to do this except with the swizzle and it seems reasonable to me I want to do this. For instance I want the the theme override twitter:card to be summary but leave the summary_large_image for both the blog and the docs. I don't see a way of doing that without the swizzle

> There is no way to set the twitter:card type for a whole layout, blog, docs, etc... it can either be set at the theme OR at the individual post level. The problem here is that it can't actually be set at the theme level because it will overwrite everything.

Indeed, as explained you can only do this with swizzle atm. We don't have an API for that, and nobody ever requested that so far. If you want to contribute this feature, I'm open, but please share a concrete use-case for using it. We don't want to introduce APIs that nobody will use.

For me, this use-case is niche enough that swizzle is a good enough workaround. We can't have first-class APIS for every single little UI tweaks that users imagine, and swizzling remains a valid option.

If there's a good-enough workaround for implementing something, and nobody used it in production yet, then it's likely that there's not enough traction for this feature to be officially implemented.

> the metadata property of the theme just doesn't really work

Yes it does, just copy-paste the docs example and see it in action. If the docs example doesn't work then it's a real bug, but please create a repro. It's hard to understand everything you claim with pure text. If I see the code, I can tell if it's the intended behavior or not, and explain why.
