### ISSUE TITLE
Docusaurus does not generate og:locale and og:locale:alternate meta tags

### ISSUE THREAD

**Issue by JavorszkyGaborOrianaWorld** [facebook/docusaurus#8887]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The built site does not have og:locale and og:locale:alternate meta tags in the Head.

### Reproducible demo

https://codesandbox.io/p/sandbox/zen-wildflower-kpuv6l?file=%2FREADME.md

### Steps to reproduce

1. Add at least two locales to docusaurus.config.js.
e.g.
```js
i18n: {
    defaultLocale: "en",
    locales: ["en", "hu"],
    localeConfigs: {
      en: {
        label: "English",
        direction: "ltr",
        htmlLang: "en-US",
        calendar: "gregory",
      },
      hu: {
        label: "Magyar",
        direction: "ltr",
        htmlLang: "hu-HU",
        calendar: "gregory",
        path: "hu",
      },
    },
  },
``` 
2. Build
3. Serve

### Expected behavior

In the built site pages in the Head tag og:locale and og:locale:alternate meta tags are present.

```html
 <meta property="og:locale" content="en_US" />
 <meta property="og:locale:alternate" content="hu_HU" />
```

### Actual behavior

In the built site pages in the Head tag og:locale and og:locale:alternate meta tags are **not** present.

### Your environment

- Public source code: no public code
- Public site URL: no public site
- Docusaurus version used: 2.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): 
  - Microsoft Edge Version 112.0.1722.39 (Official build) (64-bit)
  - node --version: v18.13.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): 
  - Edition	Windows 11 Enterprise
  - Version	22H2
  - OS build	22621.1413

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Hi @JavorszkyGaborOrianaWorld

Can you explain to me when/how this metadata is used?

We already output hreflang metadata.

See for example on https://docusaurus.io/docs/installation

```html
<html lang="en">
  <head>
    <link
      data-rh="true"
      rel="canonical"
      href="https://docusaurus.io/docs/installation"
    />
    <link
      data-rh="true"
      rel="alternate"
      href="https://docusaurus.io/docs/installation"
      hreflang="en"
    />
    <link
      data-rh="true"
      rel="alternate"
      href="https://docusaurus.io/fr/docs/installation"
      hreflang="fr"
    />
    <link
      data-rh="true"
      rel="alternate"
      href="https://docusaurus.io/pt-BR/docs/installation"
      hreflang="pt-BR"
    />
    <link
      data-rh="true"
      rel="alternate"
      href="https://docusaurus.io/ko/docs/installation"
      hreflang="ko"
    />
    <link
      data-rh="true"
      rel="alternate"
      href="https://docusaurus.io/zh-CN/docs/installation"
      hreflang="zh-CN"
    />
    <link
      data-rh="true"
      rel="alternate"
      href="https://docusaurus.io/docs/installation"
      hreflang="x-default"
    />
  </head>
</html>
```

So this looks a bit like duplicate data to me (and less complete, no URL).

Which system reads `og:locale` but does not read hreflang and html lang?

**Comment by slorber** [comment]
@jdevalk any idea? 

Should we use `og:locale:alternate` when we already have `hreflang` meta?

**Comment by jdevalk** [comment]
hey @slorber! I think we should definitely output `og:locale`, and if we can easily and reliably output `og:locale:alternate` we should. It's mentioned in Facebook's [sharing guidelines](https://developers.facebook.com/docs/sharing/webmasters/).

Unfortunately, there's not one unified standard that both Facebook and Google adhere to in these things.

**Comment by slorber** [comment]
Thanks @jdevalk , let's do this then.

Shouldn't be very hard, good issue for someone willing to contribute! (add this next to where we handle hreflang in theme)

A bit sad that we have to output duplicate info to each html page. With lots of locale that still takes a few useless bytes.

**Comment by slorber** [comment]
Just realizing that OGP is annoying by not respecting the BCP47 spec (`pt-BR` is BCP47, but ogp expects `pt_BR`)

> og:locale - The locale these tags are marked up in. Of the format language_TERRITORY. Default is en_US.
> og:locale:alternate - An [array](https://ogp.me/#array) of other locales this page is available in.

```html
<meta property="og:locale" content="en_GB" />
<meta property="og:locale:alternate" content="fr_FR" />
<meta property="og:locale:alternate" content="es_ES" />
```

Their doc is not very exhaustive but I guess wen can just to locale.replace("-","_") and call it a day.

**Comment by FlorinaPacurar** [comment]
I would like to work on this if possible

**Comment by Xebec19** [comment]
I'd like to work on this
